#!/bin/bash
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc
locale-gen
echo "LANG=en_GB.UTF-8" >> /etc/locale.conf
echo "en_GB.UTF-8 UTF-8" >> /etc/locale.gen
echo "KEYMAP=uk" >> /etc/vconsole.conf
echo "Configuring network"
echo "arch" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 arch.localdomain arch" >> /etc/hosts
cat /etc/hosts
echo "Root password:"
passwd
echo "Installing main packages"
pacman -S --noconfirm linux-lts linux-lts-headers linux-firmware intel-ucode grub sudo vim efibootmgr base-devel xdg-user-dirs xdg-utils os-prober terminus-font openssh bash-completion sudo 
#Extras
pacman -S --noconfirm neofetch vim reflector mpv youtube-dl thunar
# virtual box
sudo pacman -S --noconfirm virtualbox virtualbox-guest-utils
# Browsers
pacman -S --noconfirm firefox-ublock-origin chromium
# Xorg
pacman -S --noconfirm xorg xorg-server xorg-xinit
# Network
pacman -S --noconfirm networkmanager network-manager-applet dnsutils
# Sound
pacman -S --noconfirm alsa-utils pulseaudio
reflector -c "GB" -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist
#gpu drivers
# pacman -S  xf86-video-amdgpu
pacman -S  --noconfirm nvidia nvidia-utils nvidia-settings
echo "Configuring grub bootloader"
#uefi
# mkdir /boot/efi
# mount /dev/sda1 /boot/efi
# grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
# grub-mkconfig -o /boot/grub/grub.cfg
#bios
grub-install --target=i386-pc /dev/sda # replace sda with your disk name, not the partition
grub-mkconfig -o /boot/grub/grub.cfg
echo "Configuring base services"
systemctl enable NetworkManager
systemctl enable sshd
echo "Creating a new user"
useradd -m piplewis
echo "Password for piplewis:"
passwd piplewis
echo "piplewis ALL=(ALL) ALL" >> /etc/sudoers.d/piplewis
echo "piplewis now has sudo privilleges."
echo "Final configuration"
mkinitcpio -P
echo "Installation complete..."
