#!/bin/bash
#MUST RUN AS ROOT
mkdir /home/piplewis/.config/
cd /home/piplewis/.config
git clone https://git.suckless.org/dwm/
git clone https://git.suckless.org/dwmstatus
git clone https://git.suckless.org/st
git clone https://git.suckless.org/dmenu
pacman -Syu
pacman -S nitrogen picom lightdm  lightdm-gtk-greeter lightdm-gtk-greeter-settings archlinux-wallpaper pcmanfm avahi xdg-user-dirs xdg-utils gedit bluez bluez-utils sof-firmware
cd dwm
make
make install
cd ..
cd dwmstatus
make
make install
cd ..
cd st
make
make install
cd ..
cd dmenu
make
make install
cd
mkdir -p /usr/share/xsessions
echo "[Desktop Entry]" >> /usr/share/xsessions/dwm.desktop
echo "Encoding=UTF-8" >> /usr/share/xsessions/dwm.desktop
echo "Name=Dwm" >> /usr/share/xsessions/dwm.desktop
echo "Comment=Dynamyc window manager" >> /usr/share/xsessions/dwm.desktop
echo "Exec=dwm" >> /usr/share/xsessions/dwm.desktop
echo "Icon=dwm" >> /usr/share/xsessions/dwm.desktop
echo "Type=XSession" >> /usr/share/xsessions/dwm.desktop
#change piplewis to your username
echo "nitrogen --restore &" >> /home/piplewis/.xprofile
echo "picom -f &" >>/home/piplewis/.xprofile
cat /home/piplewis/.xprofile
systemctl enable lightdm
systemctl enable bluetooth
